### ISSUE TITLE
gcad3d was crashed on win10

### ISSUE THREAD

**Issue by rfzhu** [gcad3d/gcad3d#37] opened 2020-05-21 03:15 UTC
gcad3d version : 2.46.12
windows version : win 10

Console output : 

+++++++++++++ Start xa 2019-11-20 1
OS_hide_win
 minimize |gCAD3D|
arg[0]|C:\cad\gCAD3D\binMS32\gCAD3D.exe|
 sMax = 216
AP_get_dir__
 pwd = |C:\Users\i\AppData\Roaming|
 gcad_dir_dev = |(null)|
 gcad_dir_bas = |C:\cad\gCAD3D\|
OS_Init_ |C:\cad\gCAD3D\binMS32\gCAD3D.exe|
 bindir = |C:\cad\gCAD3D\binMS32\|
 basdir = |C:\cad\gCAD3D\|
 docdir = |C:\cad\gCAD3D\doc\|
 locdir = |C:\Users\i\AppData\Roaming\gCAD3D\|
 tmpdir = |C:\Users\i\AppData\Roaming\gCAD3D\tmp\|
 cfgdir = |C:\Users\i\AppData\Roaming\gCAD3D\cfg\|
 icodir = |C:\cad\gCAD3D\icons\|
ex-W32-OS_get_lang |ch|
 AP_lang |ch|
 _scan_- 21 |C:\cad\gCAD3D\doc\msg|
------ ex AP_lngTab_set 7
 0 |de|
 1 |en|
 2 |es|
 3 |fr|
 4 |it|
 5 |ms|
 6 |ru|
Debug-switch DDEB is ON
 local:|C:\Users\i\AppData\Roaming\gCAD3D\| base:|C:\cad\gCAD3D\|
 test configfile |C:\Users\i\AppData\Roaming\gCAD3D\cfg\gCAD3D.rc|
 L_startup_defaults:
AP_defaults_read |C:\Users\i\AppData\Roaming\gCAD3D\cfg\xa.rc|
 AP_mod_dir=|C:\Users\i\AppData\Roaming\gCAD3D\dat\|
 AP_lang=|ch|
 OS_browser=|explorer|
 AP_printer=|print|
 Modelname=|unknown.gcad|
 AP_dir_prg=|C:\Users\i\AppData\Roaming\gCAD3D\prg\|
 active application=|| 4
 AP_editor=|notepad|
 AP_winSiz=|-600,-400|
 DefaultModelsize=0.000000
 ****** ERROR AP_defaults_read - DefaultModelsize 0.000000
MSG_const_init |ch|
MSG_const__ E000-34
*** (null): cannot access C:\cad\gCAD3D\doc\msg\msg_const_ch.txt
*********** *** (null): cannot access C:\cad\gCAD3D\doc\msg\msg_const_ch.txt
**** MSG_const_init E001 C:\cad\gCAD3D\doc\msg\msg_const_ch.txt
***** MESSAGEFILE C:\cad\gCAD3D\doc\msg\msg_ch.txt DOES NOT EXIST *****OMN_init
MSG_const__ E000-0
MSG_const__ E000-1
MSG_const__ E000-2
MSG_const__ E000-3
MSG_const__ E000-4
MSG_const__ E000-5
MSG_const__ E000-6
MSG_const__ E000-7
MSG_const__ E000-8
MSG_const__ E000-9
MSG_const__ E000-10
MSG_const__ E000-11
MSG_const__ E000-12
MSG_const__ E000-13
MSG_const__ E000-14
MSG_const__ E000-15
MSG_const__ E000-16
MSG_const__ E000-17
MSG_const__ E000-18
MSG_const__ E000-19
MSG_const__ E000-20
MSG_const__ E000-21
MSG_const__ E000-22
MSG_const__ E000-23
MSG_const__ E000-24
MSG_const__ E000-25
MSG_const__ E000-26
MSG_const__ E000-27
MSG_const__ E000-28
MSG_const__ E000-29
MSG_const__ E000-30
MSG_const__ E000-31
MSG_const__ E000-32
MSG_const__ E000-33
MSG_const__ E000-34
MSG_const__ E000-35
MSG_const__ E000-36
MSG_const__ E000-37
MSG_const__ E000-38
MSG_const__ E000-39
MSG_const__ E000-40
AP_DllLst_write
PRC_lst_processors
 path-plugins=|C:\cad\gCAD3D\binMS32\plugins/|
::::DL_alloc__ 10000 240000
GTK_MAJOR_VERSION=2 GTK_MINOR_VERSION=24
Ico_init
UI_win_main 90
MSG_const__ E000-22
UI_lang_men |ch|
UI_lang_men - cannot find lang. ch - defaulted english.
*********** UI_lang_men - cannot find lang. ch - defaulted english.
***** UMB_pos__ E001
***** UME_obj_get E001
 lang-activate |獆
***** UMB_pos__ E001
***** UME_obj_get E001
MSG_const_init |ch|
MSG_const__ E000-34
*** (null): cannot access C:\cad\gCAD3D\doc\msg\msg_const_ch.txt
*********** *** (null): cannot access C:\cad\gCAD3D\doc\msg\msg_const_ch.txt
**** MSG_const_init E001 C:\cad\gCAD3D\doc\msg\msg_const_ch.txt
***** MESSAGEFILE C:\cad\gCAD3D\doc\msg\msg_ch.txt DOES NOT EXIST ***** men_hlp-L31
GL_RENDERER:    (null)
GL_VERSION:     (null)
GL_EXTENSIONS:  (null)
GLU_VERSION:    1.2.2.0 Microsoft Corporation
GLU_EXTENSIONS:
gtk_gl_area_class_init
 win_resize-|-600,-400| 600 400
MSG_const_init |ch|
MSG_const__ E000-34
*** (null): cannot access C:\cad\gCAD3D\doc\msg\msg_const_ch.txt
**** MSG_const_init E001 C:\cad\gCAD3D\doc\msg\msg_const_ch.txt
***** MESSAGEFILE C:\cad\gCAD3D\doc\msg\msg_ch.txt DOES NOT EXIST ***** gCAD3D Version 2.46.12     GUI: gtk2.24
display functions:
  -move:=Shift + drag mouse (do not push mousebuttons)
  -rotate:=Ctrl + drag mouse
  -zoom:=Shift + Ctrl + drag mouse
::::UTF_alloc__ 100 0 0
 reall > 2000004
ex-UTF_alloc__
GL_Init__ mode=0 395 224
GL_InitInfo
GL_RENDERER:    Intel(R) HD Graphics 630
GL_VERSION:     4.5.0 - Build 23.20.16.4973
GLU_VERSION:    1.2.2.0 Microsoft Corporation
GLU_EXTENSIONS: GL_EXT_bgra
 GL_DEPTH_BITS = 24
 GL_STENCIL_BITS = 8
 GL_ACCUM_RED/GREEN/BLUE/ALPHA_BITS = 16 16 16 16
 GL_RED/GREEN/BLUE/ALPHA_BITS = 8 8 8 8
 AP_stat.texture=1
AP_Get_Setup C:\Users\i\AppData\Roaming\gCAD3D\cfg\gCAD3D.rc |TEXTURE_ON|
 GL_Init0
AP_SetCol__ 147 147 173
::::GLT_alloc_pta 3 0 25000 25000
::::GLT_alloc_cta 1 0 10000 10000
::::GLT_alloc_ppa 1 0 6000 6000
::::GLU_alloc 1 0 400 400
 UI_view_Z_CB |0.0|
 UI_view_Z_CB 0.000000
UI_GR_view_set_Cen1 0.000000
TODO: let newOri = point 0,0,0 moved zVal units along constrPlane.VZ;
TODO: let constrPlane.ori = newOri;
AP_src_new
UI_PRI__ 24
::::DB_allocCDAT 0 2000000
::::DB_allocLine 0 0 5000 5000
::::DB_allocModRef 0 0 200 200
AP_Init_planes
UI_suract_keyIn 1
UI_GR_view_set_Cen1 0.000000
TODO: let newOri = point 0,0,0 moved zVal units along constrPlane.VZ;
TODO: let constrPlane.ori = newOri;
Mod_sav_i savActMdl=-1
Mod_sav_ck 0
AP_tmr_init ............
 init pipes ..
OS_CTL_read_init |C:\Users\i\AppData\Roaming\gCAD3D\tmp\CTRLpin|
 CTRL_CB__ fnSwap=|C:\Users\i\AppData\Roaming\gCAD3D\tmp\CTRLfin|
OS_CTL_write_init |C:\Users\i\AppData\Roaming\gCAD3D\tmp\CTRLpout|

(gCAD3D.exe:37500): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Error on line 1 char 113: Invalid UTF-8 encoded text in name - not valid '\xfaN\u0017\x9a`>M - GCAD, STP/STEP, IGS/IGE/IG2, DXF, 3DS, STL, LWO, WRL(VRML1), OBJ(WaveFront), TESS, BMP, JPG'

(gCAD3D.exe:37500): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Error on line 1 char 113: Invalid UTF-8 encoded text in name - not valid '\xfaN\u0017\x9a`>M - GCAD, STP/STEP, IGS/IGE/IG2, DXF, 3DS, STL, LWO, WRL(VRML1), OBJ(WaveFront), TESS, BMP, JPG'

**Comment by gcad3d** [comment] 2020-05-21 06:24
caused by:
ex-W32-OS_get_lang |ch|
- will fix that asap.

**Comment by rfzhu** [comment] 2020-05-21 09:31
> caused by:
> ex-W32-OS_get_lang |ch|
> 
> * will fix that asap.

Thank you ！

**Comment by gcad3d** [comment] 2020-05-21 11:53
issue fixed with V2.46.14.

**Closed by gcad3d** 2020-05-21 11:53 UTC
